global com.example.demo.drool.dto.Fare rideFare;
import com.example.demo.drool.dto.TaxiRide;

rule "Calculate Taxi Fare - without surcharge and short distance"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile < 100);
    then
      	rideFare.setNightSurcharge(new Long(0));
       	rideFare.setRideFare(new Long(70));
end

rule "Calculate Taxi Fare - without surcharge and long distance"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == false && distanceInMile > 100);
    then
      	rideFare.setNightSurcharge(new Long(10));
       	rideFare.setRideFare(new Long(100));
end

rule "Calculate Taxi Fare - with surcharge and short distance"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile < 100);
    then
      	rideFare.setNightSurcharge(new Long(20));
       	rideFare.setRideFare(new Long(70));
end

rule "Calculate Taxi Fare - with surcharge and long distance"
    when
        taxiRideInstance:TaxiRide(isNightSurcharge == true && distanceInMile > 100);
    then
      	rideFare.setNightSurcharge(new Long(30));
       	rideFare.setRideFare(new Long(200));
end
